### YamlMime:ManagedReference
items:
- uid: Kampute.HttpClient.MediaTypeNames.Application
  commentId: T:Kampute.HttpClient.MediaTypeNames.Application
  id: MediaTypeNames.Application
  parent: Kampute.HttpClient
  children:
  - Kampute.HttpClient.MediaTypeNames.Application.Bson
  - Kampute.HttpClient.MediaTypeNames.Application.FormUrlEncoded
  - Kampute.HttpClient.MediaTypeNames.Application.Json
  - Kampute.HttpClient.MediaTypeNames.Application.Octet
  - Kampute.HttpClient.MediaTypeNames.Application.Pdf
  - Kampute.HttpClient.MediaTypeNames.Application.Rtf
  - Kampute.HttpClient.MediaTypeNames.Application.Soap
  - Kampute.HttpClient.MediaTypeNames.Application.Xml
  - Kampute.HttpClient.MediaTypeNames.Application.Yaml
  - Kampute.HttpClient.MediaTypeNames.Application.Zip
  langs:
  - csharp
  - vb
  name: MediaTypeNames.Application
  nameWithType: MediaTypeNames.Application
  fullName: Kampute.HttpClient.MediaTypeNames.Application
  type: Class
  source:
    remote:
      path: src/Kampute.HttpClient/MediaTypeNames.cs
      branch: master
      repo: https://github.com/kampute/http-client
    id: Application
    path: src/Kampute.HttpClient/MediaTypeNames.cs
    startLine: 19
  assemblies:
  - Kampute.HttpClient
  namespace: Kampute.HttpClient
  summary: Represents media type names for application content types.
  example: []
  syntax:
    content: public static class MediaTypeNames.Application
    content.vb: Public Module MediaTypeNames.Application
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Kampute.HttpClient.MediaTypeNames.Application.Octet
  commentId: F:Kampute.HttpClient.MediaTypeNames.Application.Octet
  id: Octet
  parent: Kampute.HttpClient.MediaTypeNames.Application
  langs:
  - csharp
  - vb
  name: Octet
  nameWithType: MediaTypeNames.Application.Octet
  fullName: Kampute.HttpClient.MediaTypeNames.Application.Octet
  type: Field
  source:
    remote:
      path: src/Kampute.HttpClient/MediaTypeNames.cs
      branch: master
      repo: https://github.com/kampute/http-client
    id: Octet
    path: src/Kampute.HttpClient/MediaTypeNames.cs
    startLine: 24
  assemblies:
  - Kampute.HttpClient
  namespace: Kampute.HttpClient
  summary: Media type name for octet-stream.
  example: []
  syntax:
    content: public const string Octet = "application/octet-stream"
    return:
      type: System.String
    content.vb: Public Const Octet As String = "application/octet-stream"
- uid: Kampute.HttpClient.MediaTypeNames.Application.Pdf
  commentId: F:Kampute.HttpClient.MediaTypeNames.Application.Pdf
  id: Pdf
  parent: Kampute.HttpClient.MediaTypeNames.Application
  langs:
  - csharp
  - vb
  name: Pdf
  nameWithType: MediaTypeNames.Application.Pdf
  fullName: Kampute.HttpClient.MediaTypeNames.Application.Pdf
  type: Field
  source:
    remote:
      path: src/Kampute.HttpClient/MediaTypeNames.cs
      branch: master
      repo: https://github.com/kampute/http-client
    id: Pdf
    path: src/Kampute.HttpClient/MediaTypeNames.cs
    startLine: 29
  assemblies:
  - Kampute.HttpClient
  namespace: Kampute.HttpClient
  summary: Media type name for PDF documents.
  example: []
  syntax:
    content: public const string Pdf = "application/pdf"
    return:
      type: System.String
    content.vb: Public Const Pdf As String = "application/pdf"
- uid: Kampute.HttpClient.MediaTypeNames.Application.Rtf
  commentId: F:Kampute.HttpClient.MediaTypeNames.Application.Rtf
  id: Rtf
  parent: Kampute.HttpClient.MediaTypeNames.Application
  langs:
  - csharp
  - vb
  name: Rtf
  nameWithType: MediaTypeNames.Application.Rtf
  fullName: Kampute.HttpClient.MediaTypeNames.Application.Rtf
  type: Field
  source:
    remote:
      path: src/Kampute.HttpClient/MediaTypeNames.cs
      branch: master
      repo: https://github.com/kampute/http-client
    id: Rtf
    path: src/Kampute.HttpClient/MediaTypeNames.cs
    startLine: 34
  assemblies:
  - Kampute.HttpClient
  namespace: Kampute.HttpClient
  summary: Media type name for RTF documents.
  example: []
  syntax:
    content: public const string Rtf = "application/rtf"
    return:
      type: System.String
    content.vb: Public Const Rtf As String = "application/rtf"
- uid: Kampute.HttpClient.MediaTypeNames.Application.Soap
  commentId: F:Kampute.HttpClient.MediaTypeNames.Application.Soap
  id: Soap
  parent: Kampute.HttpClient.MediaTypeNames.Application
  langs:
  - csharp
  - vb
  name: Soap
  nameWithType: MediaTypeNames.Application.Soap
  fullName: Kampute.HttpClient.MediaTypeNames.Application.Soap
  type: Field
  source:
    remote:
      path: src/Kampute.HttpClient/MediaTypeNames.cs
      branch: master
      repo: https://github.com/kampute/http-client
    id: Soap
    path: src/Kampute.HttpClient/MediaTypeNames.cs
    startLine: 39
  assemblies:
  - Kampute.HttpClient
  namespace: Kampute.HttpClient
  summary: Media type name for SOAP payloads.
  example: []
  syntax:
    content: public const string Soap = "application/soap+xml"
    return:
      type: System.String
    content.vb: Public Const Soap As String = "application/soap+xml"
- uid: Kampute.HttpClient.MediaTypeNames.Application.Zip
  commentId: F:Kampute.HttpClient.MediaTypeNames.Application.Zip
  id: Zip
  parent: Kampute.HttpClient.MediaTypeNames.Application
  langs:
  - csharp
  - vb
  name: Zip
  nameWithType: MediaTypeNames.Application.Zip
  fullName: Kampute.HttpClient.MediaTypeNames.Application.Zip
  type: Field
  source:
    remote:
      path: src/Kampute.HttpClient/MediaTypeNames.cs
      branch: master
      repo: https://github.com/kampute/http-client
    id: Zip
    path: src/Kampute.HttpClient/MediaTypeNames.cs
    startLine: 44
  assemblies:
  - Kampute.HttpClient
  namespace: Kampute.HttpClient
  summary: Media type name for ZIP archives.
  example: []
  syntax:
    content: public const string Zip = "application/zip"
    return:
      type: System.String
    content.vb: Public Const Zip As String = "application/zip"
- uid: Kampute.HttpClient.MediaTypeNames.Application.Xml
  commentId: F:Kampute.HttpClient.MediaTypeNames.Application.Xml
  id: Xml
  parent: Kampute.HttpClient.MediaTypeNames.Application
  langs:
  - csharp
  - vb
  name: Xml
  nameWithType: MediaTypeNames.Application.Xml
  fullName: Kampute.HttpClient.MediaTypeNames.Application.Xml
  type: Field
  source:
    remote:
      path: src/Kampute.HttpClient/MediaTypeNames.cs
      branch: master
      repo: https://github.com/kampute/http-client
    id: Xml
    path: src/Kampute.HttpClient/MediaTypeNames.cs
    startLine: 52
  assemblies:
  - Kampute.HttpClient
  namespace: Kampute.HttpClient
  summary: Media type name for XML data.
  example: []
  syntax:
    content: public const string Xml = "application/xml"
    return:
      type: System.String
    content.vb: Public Const Xml As String = "application/xml"
- uid: Kampute.HttpClient.MediaTypeNames.Application.Json
  commentId: F:Kampute.HttpClient.MediaTypeNames.Application.Json
  id: Json
  parent: Kampute.HttpClient.MediaTypeNames.Application
  langs:
  - csharp
  - vb
  name: Json
  nameWithType: MediaTypeNames.Application.Json
  fullName: Kampute.HttpClient.MediaTypeNames.Application.Json
  type: Field
  source:
    remote:
      path: src/Kampute.HttpClient/MediaTypeNames.cs
      branch: master
      repo: https://github.com/kampute/http-client
    id: Json
    path: src/Kampute.HttpClient/MediaTypeNames.cs
    startLine: 61
  assemblies:
  - Kampute.HttpClient
  namespace: Kampute.HttpClient
  summary: Media type name for JSON data.
  example: []
  syntax:
    content: public const string Json = "application/json"
    return:
      type: System.String
    content.vb: Public Const Json As String = "application/json"
- uid: Kampute.HttpClient.MediaTypeNames.Application.Bson
  commentId: F:Kampute.HttpClient.MediaTypeNames.Application.Bson
  id: Bson
  parent: Kampute.HttpClient.MediaTypeNames.Application
  langs:
  - csharp
  - vb
  name: Bson
  nameWithType: MediaTypeNames.Application.Bson
  fullName: Kampute.HttpClient.MediaTypeNames.Application.Bson
  type: Field
  source:
    remote:
      path: src/Kampute.HttpClient/MediaTypeNames.cs
      branch: master
      repo: https://github.com/kampute/http-client
    id: Bson
    path: src/Kampute.HttpClient/MediaTypeNames.cs
    startLine: 67
  assemblies:
  - Kampute.HttpClient
  namespace: Kampute.HttpClient
  summary: Media type name for BSON data.
  example: []
  syntax:
    content: public const string Bson = "application/bson"
    return:
      type: System.String
    content.vb: Public Const Bson As String = "application/bson"
- uid: Kampute.HttpClient.MediaTypeNames.Application.Yaml
  commentId: F:Kampute.HttpClient.MediaTypeNames.Application.Yaml
  id: Yaml
  parent: Kampute.HttpClient.MediaTypeNames.Application
  langs:
  - csharp
  - vb
  name: Yaml
  nameWithType: MediaTypeNames.Application.Yaml
  fullName: Kampute.HttpClient.MediaTypeNames.Application.Yaml
  type: Field
  source:
    remote:
      path: src/Kampute.HttpClient/MediaTypeNames.cs
      branch: master
      repo: https://github.com/kampute/http-client
    id: Yaml
    path: src/Kampute.HttpClient/MediaTypeNames.cs
    startLine: 72
  assemblies:
  - Kampute.HttpClient
  namespace: Kampute.HttpClient
  summary: Media type name for YAML data.
  example: []
  syntax:
    content: public const string Yaml = "application/yaml"
    return:
      type: System.String
    content.vb: Public Const Yaml As String = "application/yaml"
- uid: Kampute.HttpClient.MediaTypeNames.Application.FormUrlEncoded
  commentId: F:Kampute.HttpClient.MediaTypeNames.Application.FormUrlEncoded
  id: FormUrlEncoded
  parent: Kampute.HttpClient.MediaTypeNames.Application
  langs:
  - csharp
  - vb
  name: FormUrlEncoded
  nameWithType: MediaTypeNames.Application.FormUrlEncoded
  fullName: Kampute.HttpClient.MediaTypeNames.Application.FormUrlEncoded
  type: Field
  source:
    remote:
      path: src/Kampute.HttpClient/MediaTypeNames.cs
      branch: master
      repo: https://github.com/kampute/http-client
    id: FormUrlEncoded
    path: src/Kampute.HttpClient/MediaTypeNames.cs
    startLine: 77
  assemblies:
  - Kampute.HttpClient
  namespace: Kampute.HttpClient
  summary: Media type name for form URL encoded data.
  example: []
  syntax:
    content: public const string FormUrlEncoded = "application/x-www-form-urlencoded"
    return:
      type: System.String
    content.vb: Public Const FormUrlEncoded As String = "application/x-www-form-urlencoded"
references:
- uid: Kampute.HttpClient
  commentId: N:Kampute.HttpClient
  href: Kampute.html
  name: Kampute.HttpClient
  nameWithType: Kampute.HttpClient
  fullName: Kampute.HttpClient
  spec.csharp:
  - uid: Kampute
    name: Kampute
    href: Kampute.html
  - name: .
  - uid: Kampute.HttpClient
    name: HttpClient
    href: Kampute.HttpClient.html
  spec.vb:
  - uid: Kampute
    name: Kampute
    href: Kampute.html
  - name: .
  - uid: Kampute.HttpClient
    name: HttpClient
    href: Kampute.HttpClient.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
