// Copyright (C) 2025 Kampute
//
// This file is part of the Kampute.HttpClient package and is released under the terms of the MIT license.
// See the LICENSE file in the project root for the full license text.

namespace Kampute.HttpClient
{
    /// <summary>
    /// Provides constants for common HTTP authentication schemes.
    /// </summary>
    public static class AuthSchemes
    {
        /// <summary>
        /// The Bearer authentication scheme as defined in RFC 6750.
        /// This scheme is typically used with OAuth 2.0. The bearer token is a cryptic string, usually generated by the server in response to a login request.
        /// </summary>
        public const string Bearer = "Bearer";

        /// <summary>
        /// The Basic authentication scheme as defined in RFC 7617.
        /// This scheme transmits credentials as user ID/password pairs, encoded using Base64.
        /// </summary>
        public const string Basic = "Basic";

        /// <summary>
        /// The Digest authentication scheme as defined in RFC 7616.
        /// This scheme is an enhancement of the Basic scheme, providing a more secure approach to user authentication.
        /// </summary>
        public const string Digest = "Digest";

        /// <summary>
        /// The HOBA (HTTP Origin-Bound Authentication) scheme as defined in RFC 7486.
        /// This scheme is a token-based authentication method that binds a token to the origin of the HTTP request.
        /// </summary>
        public const string HOBA = "HOBA";

        /// <summary>
        /// The Mutual authentication scheme. 
        /// This scheme is a method where both the client and server authenticate each other.
        /// Note that this is not defined in an RFC and the usage may vary.
        /// </summary>
        public const string Mutual = "Mutual";

        /// <summary>
        /// The AWS4-HMAC-SHA256 authentication scheme. 
        /// This scheme is specific to Amazon Web Services and is used for signing API requests.
        /// </summary>
        public const string AWS4HMACSHA256 = "AWS4-HMAC-SHA256";

        /// <summary>
        /// The API Key authentication scheme.
        /// In this scheme, a secret API key is included in the HTTP request.
        /// </summary>
        public const string ApiKey = "ApiKey";
    }
}
