// Copyright (C) 2024 Kampute
//
// This file is part of the Kampute.HttpClient package and is released under the terms of the MIT license.
// See the LICENSE file in the project root for the full license text.

namespace Kampute.HttpClient
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Provides extension methods for dictionaries to simplify accessing and manipulating their entries.
    /// </summary>
    public static class DictionaryExtensions
    {
        /// <summary>
        /// Attempts to retrieve the value associated with the specified key from the dictionary and cast it to the type <typeparamref name="T"/>.
        /// </summary>
        /// <typeparam name="T">The type to which the value should be cast.</typeparam>
        /// <param name="dictionary">The dictionary to search.</param>
        /// <param name="key">The key of the value to retrieve.</param>
        /// <param name="value">
        /// When this method returns, contains the value associated with the specified key if the operation is successful and the value is of type <typeparamref name="T"/>; otherwise, 
        /// the default value for <typeparamref name="T"/>. This parameter is passed uninitialized.
        /// </param>
        /// <returns><c>true</c> if the dictionary contains an element with the specified key and the value is of type <typeparamref name="T"/>; otherwise, <c>false</c>.</returns>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="key"/> is <c>null</c>.</exception>
        public static bool TryGetValue<T>(this IDictionary<string, object?> dictionary, string key, out T? value)
        {
            if (key is null)
                throw new ArgumentNullException(nameof(key));

            if (dictionary.TryGetValue(key, out var v) && v is T typedValue)
            {
                value = typedValue;
                return true;
            }

            value = default;
            return false;
        }

        /// <summary>
        /// Adds a key/value pair to the dictionary if the key does not already exist, or updates the existing key with a new value generated by the provided delegate.
        /// </summary>
        /// <typeparam name="T">The type of the value to add or update in the dictionary.</typeparam>
        /// <param name="dictionary">The dictionary to add or update the key/value pair in.</param>
        /// <param name="key">The key of the element to add or update.</param>
        /// <param name="valueFactory">The function used to generate a value for the key if the key does not exist in the dictionary.</param>
        /// <returns>
        /// The value associated with the specified key. This will be either the existing value for the key if the key is found in the dictionary, or the new value 
        /// if the key was not found and a new key/value pair was added.
        /// </returns>
        /// <exception cref="ArgumentNullException">Thrown if either <paramref name="key"/> or <paramref name="valueFactory"/> is <c>null</c>.</exception>
        public static T GetOrAdd<T>(this IDictionary<string, object?> dictionary, string key, Func<string, T> valueFactory)
        {
            if (key is null)
                throw new ArgumentNullException(nameof(key));
            if (valueFactory is null)
                throw new ArgumentNullException(nameof(valueFactory));

            if (!dictionary.TryGetValue(key, out var v) || v is not T value)
            {
                value = valueFactory(key);
                dictionary[key] = value;
            }

            return value;
        }
    }
}
